//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketR.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_View
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Deal_View1 { get; set; }
        public Nullable<bool> User_Table_Access { get; set; }
        public Nullable<bool> Receive_Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
