//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketR.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewFileRecords2
    {
        public int RecordID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string N { get; set; }
        public string DEAL_ID { get; set; }
        public string ON_OFF_BALANCE { get; set; }
        public string DEAL_TYPE { get; set; }
        public string PROD_TYPE { get; set; }
        public string PAY_RECIEVE { get; set; }
        public string CCY { get; set; }
        public Nullable<double> NOTIONAL { get; set; }
        public string MATURITY_DATE { get; set; }
        public string INTEREST_TYPE { get; set; }
        public string FIXING_DATE { get; set; }
        public string INT_CHANGE_FREQ { get; set; }
        public string INT_CHAGE_TERM { get; set; }
        public Nullable<double> INT_PRE { get; set; }
        public Nullable<double> NPV_DELTA_ILS { get; set; }
        public string NETED { get; set; }
        public string NETED_ID { get; set; }
        public string Portfolio { get; set; }
        public string NETTING_COUNTER { get; set; }
        public string CONTRACT_MAT_DATE { get; set; }
        public string validity_date { get; set; }
        public Nullable<bool> Sim_Liquidate_flag { get; set; }
    
        public virtual FileHistory FileHistory { get; set; }
    }
}
