//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketR.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comp2
    {
        public int ID { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public Nullable<double> ILS { get; set; }
        public Nullable<double> USD { get; set; }
        public Nullable<double> EUR { get; set; }
        public Nullable<double> GBP { get; set; }
        public Nullable<double> CHF { get; set; }
        public Nullable<double> JPY { get; set; }
        public Nullable<double> Other { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
