//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketR.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventLog
    {
        public int LogID { get; set; }
        public string UserId { get; set; }
        public string Event { get; set; }
        public string Status { get; set; }
        public System.DateTime LoggedDate { get; set; }
    }
}
