//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderPermission
    {
        public int Deal_N { get; set; }
        public string Deal_Type { get; set; }
        public string MTM { get; set; }
        public string Folder { get; set; }
    }
}
